#
# Global Makefile to build all mTCP apps
#

APPS = dhcp dnstest ftp ftpsrv htget ircjr nc netdrv ping pkttool sample sntp spdtest telnet

all: $(APPS)

dhcp: .symbolic
	cd dhcp && wmake

dnstest: .symbolic
	cd dnstest && wmake

ftp: .symbolic
	cd ftp && wmake

ftpsrv: .symbolic
	cd ftpsrv && wmake

htget: .symbolic
	cd htget && wmake

ircjr: .symbolic
	cd ircjr && wmake

nc: .symbolic
	cd nc && wmake

netdrv: .symbolic
	cd netdrv && wmake

ping: .symbolic
	cd ping && wmake

pkttool: .symbolic
	cd pkttool && wmake

sample: .symbolic
	cd sample && wmake

sntp: .symbolic
	cd sntp && wmake

spdtest: .symbolic
	cd spdtest && wmake

telnet: .symbolic
	cd telnet && wmake

